kafka:
  broker: kafka-top-stories-top-stories.j.aivencloud.com:19196
  topic: hn-stories
  consumer_group: story-api-top
  ca_cert_path: ../certs-and-keys/ca.pem
  client_cert_path: ../certs-and-keys/service.cert
  client_key_path: ../certs-and-keys/service.key

api:
  port: 8083

# Consume only high-scoring stories (score >= 100)
filter:
  story_types: []
  keywords: []
  minimum_score: 100
